unique_ids:
  assets:
    standard-page.html: 3VRMKHIG6OWN4YO3YHK3BUGAYUZNHHXG
    theme.css: CVIO4WXPRXFKUUZR6KBC3X4H6QWDA3V7
  forms:
    Form1: UHNFPKD6PMCTBH4CATJ5GO5ZWIEDRLRF
  modules: {}
  scripts: {}
  server_modules: {}
